rpm: argv.h File Reference
argv.h File Reference
#include <stdio.h>
#include <rpm/rpmtypes.h>
Data Structures
struct ARGI_s
Typedefs
typedef char ** ARGV_t
typedef char *const * ARGV_const_t
typedef int * ARGint_t
typedef struct ARGI_s * ARGI_t
typedef struct ARGI_s const *const ARGI_const_t
typedef rpmFlags argvFlags
Enumerations
enum argvFlags_e { ARGV_NONE = 0, ARGV_SKIPEMPTY = (1 << 0) }
Functions
void argvPrint (const char *msg, ARGV_const_t argv, FILE *fp)
Print argv array elements.
ARGI_t argiFree (ARGI_t argi)
Destroy an argi array.
ARGV_t argvNew (void)
Create an empty argv array.
ARGV_t argvFree (ARGV_t argv)
Destroy an argv array.
int argiCount (ARGI_const_t argi)
Return no.
ARGint_t argiData (ARGI_const_t argi)
Return data from argi array.
int argvCount (ARGV_const_t argv)
Return no.
ARGV_t argvData (ARGV_t argv)
Return data from argv array.
int argvCmp (const void *a, const void *b)
Compare argv arrays (qsort/bsearch).
int argvSort (ARGV_t argv, int(*compar)(const void *, const void *))
Sort an argv array.
ARGV_t argvSearch (ARGV_const_t argv, const char *val, int(*compar)(const void *, const void *))
Find an element in an argv array.
int argiAdd (ARGI_t *argip, int ix, int val)
Add an int to an argi array.
int argvAdd (ARGV_t *argvp, const char *val)
Add a string to an argv array.
int argvAddNum (ARGV_t *argvp, int val)
Add a number to an argv array (converting to a string).
int argvAppend (ARGV_t *argvp, ARGV_const_t av)
Append one argv array to another.
ARGV_t argvSplitString (const char *str, const char *seps, argvFlags flags)
Split a string into an argv array.
int argvSplit (ARGV_t *argvp, const char *str, const char *seps)
Split a string into an argv array.
char * argvJoin (ARGV_const_t argv, const char *sep)
Join an argv array into a string.
Typedef Documentation
typedef struct ARGI_s const* const ARGI_const_t
Definition at line 24 of file argv.h.
typedef struct ARGI_s* ARGI_t
Definition at line 23 of file argv.h.
typedef int* ARGint_t
Definition at line 18 of file argv.h.
typedef char* const* ARGV_const_t
Definition at line 16 of file argv.h.
typedef char** ARGV_t
Definition at line 15 of file argv.h.
typedef rpmFlags argvFlags
Definition at line 147 of file argv.h.
Enumeration Type Documentation
enum argvFlags_e
Enumerator
ARGV_NONE
ARGV_SKIPEMPTY
Definition at line 142 of file argv.h.
Function Documentation
int argiAdd (ARGI_t * argip, int ix, int val)
Add an int to an argi array.
Return values
*argip argi array
Parameters
ix argi array index (or -1 to append)
val int arg to add
Returns
0 always
int argiCount (ARGI_const_t argi)
Return no.
of elements in argi array.
Parameters
argi argi array
Returns
no. of elements
ARGint_t argiData (ARGI_const_t argi)
Return data from argi array.
Parameters
argi argi array
Returns
argi array data address
ARGI_t argiFree (ARGI_t argi)
Destroy an argi array.
Parameters
argi argi array
Returns
NULL always
int argvAdd (ARGV_t * argvp, const char * val)
Add a string to an argv array.
Return values
*argvp argv array
Parameters
val string arg to append
Returns
0 always
int argvAddNum (ARGV_t * argvp, int val)
Add a number to an argv array (converting to a string).
Return values
*argvp argv array
Parameters
val numeric arg to append
Returns
0 always
int argvAppend (ARGV_t * argvp, ARGV_const_t av)
Append one argv array to another.
Return values
*argvp argv array
Parameters
av argv array to append
Returns
0 always
int argvCmp (const void * a, const void * b)
Compare argv arrays (qsort/bsearch).
Parameters
a 1st instance address
b 2nd instance address
Returns
result of comparison
int argvCount (ARGV_const_t argv)
Return no.
of elements in argv array.
Parameters
argv argv array
Returns
no. of elements
ARGV_t argvData (ARGV_t argv)
Return data from argv array.
Parameters
argv argv array
Returns
argv array data address
ARGV_t argvFree (ARGV_t argv)
Destroy an argv array.
Parameters
argv argv array
Returns
NULL always
Referenced by main().
char* argvJoin (ARGV_const_t argv, const char * sep)
Join an argv array into a string.
Parameters
*argv argv array to join
sep separator string to use
Returns
malloc'ed string
Referenced by build().
ARGV_t argvNew (void)
Create an empty argv array.
Returns
pointer to empty argv
void argvPrint (const char * msg, ARGV_const_t argv, FILE * fp)
Print argv array elements.
Parameters
msg output message prefix (or NULL)
argv argv array
fp output file handle (NULL uses stderr)
ARGV_t argvSearch (ARGV_const_t argv, const char * val, int(*)(const void *, const void *) compar)
Find an element in an argv array.
Parameters
argv argv array
val string to find
compar strcmp-like comparison function, or NULL for argvCmp()
Returns
found string (NULL on failure)
int argvSort (ARGV_t argv, int(*)(const void *, const void *) compar)
Sort an argv array.
Parameters
argv argv array
compar strcmp-like comparison function, or NULL for argvCmp()
Returns
0 always
int argvSplit (ARGV_t * argvp, const char * str, const char * seps)
Split a string into an argv array.
Return values
*argvp argv array
Parameters
str string arg to split
seps separator characters
Returns
0 always
Referenced by buildArgCallback().
ARGV_t argvSplitString (const char * str, const char * seps, argvFlags flags)
Split a string into an argv array.
Parameters
str string arg to split
seps separator characters
flags flags to control behavior
Returns
argv array