rpm: lex.yy.c File Reference
lex.yy.c File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include "parseReqs.tab.h"
#include <unistd.h>
Data Structures
struct yy_buffer_state
struct yy_trans_info
Macros
#define YY_INT_ALIGNED short int
#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#define FLEX_BETA
#define FLEXINT_H
#define INT8_MIN (-128)
#define INT16_MIN (-32767-1)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT16_MAX (32767)
#define INT32_MAX (2147483647)
#define UINT8_MAX (255U)
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define yyconst
#define YY_NULL 0
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define BEGIN (yy_start) = 1 + 2 *
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_NEW_FILE yyrestart(yyin)
#define YY_END_OF_BUFFER_CHAR 0
#define YY_BUF_SIZE 16384
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_SIZE_T
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define YY_LESS_LINENO(n)
#define yyless(n)
#define unput(c) yyunput(c, (yytext_ptr))
#define YY_STRUCT_YY_BUFFER_STATE
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define YY_BUFFER_EOF_PENDING 2
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)
#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)
#define yy_set_bol(at_bol)
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define yytext_ptr yytext
#define YY_DO_BEFORE_ACTION
#define YY_NUM_RULES 9
#define YY_END_OF_BUFFER 10
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#define INITIAL 0
#define YY_EXTRA_TYPE void *
#define YY_READ_BUF_SIZE 8192
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
#define YY_INPUT(buf, result, max_size)
#define yyterminate() return YY_NULL
#define YY_START_STACK_INCR 25
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#define YY_DECL_IS_OURS 1
#define YY_DECL int yylex (void)
#define YY_USER_ACTION
#define YY_BREAK break;
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_EXIT_FAILURE 2
#define yyless(n)
#define YYTABLES_NAME "yytables"
Typedefs
typedef signed char flex_int8_t
typedef short int flex_int16_t
typedef int flex_int32_t
typedef unsigned char flex_uint8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef size_t yy_size_t
typedef unsigned char YY_CHAR
typedef int yy_state_type
Functions
void yyrestart (FILE *input_file)
Immediately switch to a different input stream.
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
Switch to a different input buffer.
YY_BUFFER_STATE yy_create_buffer (FILE *file, int size)
Allocate and initialize an input buffer state.
void yy_delete_buffer (YY_BUFFER_STATE b)
Destroy the buffer.
void yy_flush_buffer (YY_BUFFER_STATE b)
Discard all buffered characters.
void yypush_buffer_state (YY_BUFFER_STATE new_buffer)
Pushes the new state onto the stack.
void yypop_buffer_state (void)
Removes and deletes the top of the stack, if present.
static void yyensure_buffer_stack (void)
static void yy_load_buffer_state (void)
static void yy_init_buffer (YY_BUFFER_STATE b, FILE *file)
YY_BUFFER_STATE yy_scan_buffer (char *base, yy_size_t size)
Setup the input buffer state to scan directly from a user-specified character buffer.
YY_BUFFER_STATE yy_scan_string (char *yystr)
Setup the input buffer state to scan a string.
YY_BUFFER_STATE yy_scan_bytes (char *yybytes, yy_size_t _yybytes_len)
Setup the input buffer state to scan the given bytes.
void * yyalloc (yy_size_t)
void * yyrealloc (void *, yy_size_t)
void yyfree (void *)
static yy_state_type yy_get_previous_state (void)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state)
static int yy_get_next_buffer (void)
static void yy_fatal_error (char msg[])
static int yy_init_globals (void)
int yylex_destroy (void)
int yyget_debug (void)
void yyset_debug (int debug_flag)
void * yyget_extra (void)
void yyset_extra (void *user_defined)
FILE * yyget_in (void)
Get the input stream.
void yyset_in (FILE *in_str)
Set the input stream.
FILE * yyget_out (void)
Get the output stream.
void yyset_out (FILE *out_str)
yy_size_t yyget_leng (void)
Get the length of the current token.
char * yyget_text (void)
Get the current token.
int yyget_lineno (void)
Get the current line number.
void yyset_lineno (int line_number)
Set the current line number.
int yywrap (void)
static void yyunput (int c, char *buf_ptr)
static int input (void)
int yylex (void)
The main scanner function which does all the work.
static void yyunput (int c, register char *yy_bp)
static void yy_fatal_error (char *msg)
Variables
yy_size_t yyleng
FILE * yyin = (FILE *) 0
FILE * yyout = (FILE *) 0
static size_t yy_buffer_stack_top = 0
index of top of stack.
static size_t yy_buffer_stack_max = 0
capacity of stack.
static YY_BUFFER_STATE * yy_buffer_stack = 0
Stack as an array.
static char yy_hold_char
static yy_size_t yy_n_chars
static char * yy_c_buf_p = (char *) 0
static int yy_init = 0
static int yy_start = 0
static int yy_did_buffer_switch_on_eof
int yylineno = 1
char * yytext
static flex_int16_t yy_accept [21]
static flex_int32_t yy_ec [256]
static flex_int32_t yy_meta [16]
static flex_int16_t yy_base [22]
static flex_int16_t yy_def [22]
static flex_int16_t yy_nxt [40]
static flex_int16_t yy_chk [40]
static yy_state_type yy_last_accepting_state
static char * yy_last_accepting_cpos
int yy_flex_debug = 0
Macro Definition Documentation
#define BEGIN (yy_start) = 1 + 2 *
Definition at line 125 of file lex.yy.c.
#define ECHO do { if (fwrite(yytext, yyleng, 1, yyout)) {} } while (0)
Definition at line 552 of file lex.yy.c.
Referenced by yylex().
#define EOB_ACT_CONTINUE_SCAN 0
Definition at line 165 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), and yylex().
#define EOB_ACT_END_OF_FILE 1
Definition at line 166 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), and yylex().
#define EOB_ACT_LAST_MATCH 2
Definition at line 167 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), and yylex().
#define FLEX_BETA
Definition at line 13 of file lex.yy.c.
#define FLEX_SCANNER
Definition at line 8 of file lex.yy.c.
#define FLEXINT_H
Definition at line 29 of file lex.yy.c.
#define INITIAL 0
Definition at line 465 of file lex.yy.c.
Referenced by yylex().
#define INT16_MAX (32767)
Definition at line 71 of file lex.yy.c.
#define INT16_MIN (-32767-1)
Definition at line 62 of file lex.yy.c.
#define INT32_MAX (2147483647)
Definition at line 74 of file lex.yy.c.
#define INT32_MIN (-2147483647-1)
Definition at line 65 of file lex.yy.c.
#define INT8_MAX (127)
Definition at line 68 of file lex.yy.c.
#define INT8_MIN (-128)
Definition at line 59 of file lex.yy.c.
#define REJECT reject_used_but_not_detected
Definition at line 455 of file lex.yy.c.
#define UINT16_MAX (65535U)
Definition at line 80 of file lex.yy.c.
#define UINT32_MAX (4294967295U)
Definition at line 83 of file lex.yy.c.
#define UINT8_MAX (255U)
Definition at line 77 of file lex.yy.c.
#define unput (c) yyunput(c, (yytext_ptr))
Definition at line 185 of file lex.yy.c.
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
Definition at line 331 of file lex.yy.c.
#define YY_BREAK break;
Definition at line 631 of file lex.yy.c.
Referenced by yylex().
#define YY_BUF_SIZE 16384
Definition at line 144 of file lex.yy.c.
Referenced by yylex(), and yyrestart().
#define YY_BUFFER_EOF_PENDING 2
Definition at line 247 of file lex.yy.c.
Referenced by yy_get_next_buffer().
#define YY_BUFFER_NEW 0
Definition at line 235 of file lex.yy.c.
Referenced by yy_flush_buffer(), yy_scan_buffer(), and yylex().
#define YY_BUFFER_NORMAL 1
Definition at line 236 of file lex.yy.c.
Referenced by yylex().
#define YY_CURRENT_BUFFER
Value:
((yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
Definition at line 263 of file lex.yy.c.
Referenced by yy_delete_buffer(), yy_flush_buffer(), yy_init_buffer(), yy_switch_to_buffer(), yylex(), yylex_destroy(), yypop_buffer_state(), yypush_buffer_state(), and yyrestart().
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
Definition at line 270 of file lex.yy.c.
Referenced by input(), yy_delete_buffer(), yy_get_next_buffer(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex(), yylex_destroy(), yypop_buffer_state(), yypush_buffer_state(), yyrestart(), and yyunput().
#define YY_DECL int yylex (void)
Definition at line 619 of file lex.yy.c.
#define YY_DECL_IS_OURS 1
Definition at line 615 of file lex.yy.c.
#define YY_DO_BEFORE_ACTION
Value:
(yytext_ptr) = yy_bp; \
    yyleng = (size_t) (yy_cp - yy_bp); \
        (yy_hold_char) = *yy_cp; \
        *yy_cp = '\0'; \
        (yy_c_buf_p) = yy_cp;
Definition at line 356 of file lex.yy.c.
Referenced by yylex().
#define YY_END_OF_BUFFER 10
Definition at line 364 of file lex.yy.c.
Referenced by yylex().
#define YY_END_OF_BUFFER_CHAR 0
Definition at line 140 of file lex.yy.c.
Referenced by input(), yy_flush_buffer(), yy_get_next_buffer(), yy_scan_buffer(), and yy_scan_bytes().
#define YY_EXIT_FAILURE 2
Definition at line 1566 of file lex.yy.c.
Referenced by yy_fatal_error().
#define YY_EXTRA_TYPE void *
Definition at line 476 of file lex.yy.c.
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg)
Definition at line 606 of file lex.yy.c.
Referenced by yy_create_buffer(), yy_get_next_buffer(), yy_scan_buffer(), yy_scan_bytes(), yyensure_buffer_stack(), yylex(), and yyunput().
#define YY_FLEX_MAJOR_VERSION 2
Definition at line 9 of file lex.yy.c.
#define YY_FLEX_MINOR_VERSION 5
Definition at line 10 of file lex.yy.c.
#define YY_FLEX_SUBMINOR_VERSION 37
Definition at line 11 of file lex.yy.c.
#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER)
Definition at line 299 of file lex.yy.c.
#define YY_INPUT (buf, result, max_size)
Value:
if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) \
                { \
                int c = '*'; \
                size_t n; \
                for ( n = 0; n < max_size && \
                             (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
                        buf[n] = (char) c; \
                if ( c == '\n' ) \
                        buf[n++] = (char) c; \
                if ( c == EOF && ferror( yyin ) ) \
                        YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else \
                { \
                errno=0; \
                while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
                        { \
                        if( errno != EINTR) \
                                { \
                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                                break; \
                                } \
                        errno=0; \
                        clearerr(yyin); \
                        } \
                }\
\
Definition at line 559 of file lex.yy.c.
Referenced by yy_get_next_buffer().
#define YY_INT_ALIGNED short int
Definition at line 4 of file lex.yy.c.
#define YY_LESS_LINENO (n)
Definition at line 169 of file lex.yy.c.
#define YY_MORE_ADJ 0
Definition at line 457 of file lex.yy.c.
Referenced by yy_get_next_buffer(), yy_get_previous_state(), and yylex().
#define yy_new_buffer yy_create_buffer
Definition at line 309 of file lex.yy.c.
#define YY_NEW_FILE yyrestart(yyin)
Definition at line 138 of file lex.yy.c.
Referenced by input(), and yylex().
#define YY_NULL 0
Definition at line 112 of file lex.yy.c.
#define YY_NUM_RULES 9
Definition at line 363 of file lex.yy.c.
#define YY_READ_BUF_SIZE 8192
Definition at line 544 of file lex.yy.c.
Referenced by yy_get_next_buffer().
#define YY_RESTORE_YY_MORE_OFFSET
Definition at line 458 of file lex.yy.c.
Referenced by yylex().
#define YY_RULE_SETUP YY_USER_ACTION
Definition at line 634 of file lex.yy.c.
Referenced by yylex().
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
Definition at line 119 of file lex.yy.c.
Referenced by yy_get_previous_state(), and yylex().
#define yy_set_bol (at_bol)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
        YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
        } \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
        }
Definition at line 321 of file lex.yy.c.
#define yy_set_interactive (is_interactive)
Value:
{ \
        if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
        YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
        } \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
        }
Definition at line 311 of file lex.yy.c.
#define YY_START (((yy_start) - 1) / 2)
Definition at line 131 of file lex.yy.c.
Referenced by yylex().
#define YY_START_STACK_INCR 25
Definition at line 601 of file lex.yy.c.
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
Definition at line 149 of file lex.yy.c.
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
Definition at line 135 of file lex.yy.c.
Referenced by yylex().
#define YY_STRUCT_YY_BUFFER_STATE
Definition at line 188 of file lex.yy.c.
#define YY_TYPEDEF_YY_BUFFER_STATE
Definition at line 152 of file lex.yy.c.
#define YY_TYPEDEF_YY_SIZE_T
Definition at line 157 of file lex.yy.c.
#define YY_USER_ACTION
Definition at line 626 of file lex.yy.c.
#define yyconst
Definition at line 108 of file lex.yy.c.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
                *yy_cp = (yy_hold_char); \
        YY_RESTORE_YY_MORE_OFFSET \
                (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
                } \
        while ( 0 )
Definition at line 1578 of file lex.yy.c.
#define yyless (n)
Value:
do \
                { \
                /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        yytext[yyleng] = (yy_hold_char); \
                (yy_c_buf_p) = yytext + yyless_macro_arg; \
                (yy_hold_char) = *(yy_c_buf_p); \
                *(yy_c_buf_p) = '\0'; \
        yyleng = yyless_macro_arg; \
                } \
        while ( 0 )
Definition at line 1578 of file lex.yy.c.
#define yymore () yymore_used_but_not_detected
Definition at line 456 of file lex.yy.c.
#define YYSTATE YY_START
Definition at line 132 of file lex.yy.c.
#define YYTABLES_NAME "yytables"
Definition at line 1768 of file lex.yy.c.
#define yyterminate () return YY_NULL
Definition at line 596 of file lex.yy.c.
Referenced by yylex().
#define yytext_ptr yytext
Definition at line 346 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), yy_get_previous_state(), yy_load_buffer_state(), yylex(), and yyunput().
Typedef Documentation
typedef short int flex_int16_t
Definition at line 51 of file lex.yy.c.
typedef int flex_int32_t
Definition at line 52 of file lex.yy.c.
typedef signed char flex_int8_t
Definition at line 50 of file lex.yy.c.
typedef unsigned short int flex_uint16_t
Definition at line 54 of file lex.yy.c.
typedef unsigned int flex_uint32_t
Definition at line 55 of file lex.yy.c.
typedef unsigned char flex_uint8_t
Definition at line 53 of file lex.yy.c.
typedef struct yy_buffer_state* YY_BUFFER_STATE
Definition at line 153 of file lex.yy.c.
typedef unsigned char YY_CHAR
Definition at line 335 of file lex.yy.c.
typedef size_t yy_size_t
Definition at line 158 of file lex.yy.c.
typedef int yy_state_type
Definition at line 339 of file lex.yy.c.
Function Documentation
static int input (void) static
Definition at line 1146 of file lex.yy.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yy_hold_char, yy_n_chars, YY_NEW_FILE, yyin, yyrestart(), yytext_ptr, and yywrap().
YY_BUFFER_STATE yy_create_buffer (FILE * file, int size)
Allocate and initialize an input buffer state.
Parameters
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
Returns
the allocated buffer state.
Definition at line 1283 of file lex.yy.c.
References yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, yy_init_buffer(), yy_buffer_state::yy_is_our_buffer, and yyalloc().
Referenced by yylex(), and yyrestart().
void yy_delete_buffer (YY_BUFFER_STATE b)
Destroy the buffer.
Parameters
b a buffer created with yy_create_buffer()
Definition at line 1311 of file lex.yy.c.
References yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_buffer_state::yy_is_our_buffer, and yyfree().
Referenced by yylex_destroy(), and yypop_buffer_state().
static void yy_fatal_error (char msg[]) static
static void yy_fatal_error (char * msg) static
Definition at line 1569 of file lex.yy.c.
References YY_EXIT_FAILURE.
void yy_flush_buffer (YY_BUFFER_STATE b)
Discard all buffered characters.
On the next scan, YY_INPUT will be called.
Parameters
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
Definition at line 1358 of file lex.yy.c.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, yy_load_buffer_state(), and yy_buffer_state::yy_n_chars.
Referenced by yy_init_buffer().
static int yy_get_next_buffer (void) static
Definition at line 916 of file lex.yy.c.
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, source, yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yy_n_chars, YY_READ_BUF_SIZE, yyin, yyrealloc(), yyrestart(), and yytext_ptr.
Referenced by input(), and yylex().
static yy_state_type yy_get_previous_state (void) static
Definition at line 1050 of file lex.yy.c.
References yy_c_buf_p, yy_last_accepting_cpos, yy_last_accepting_state, YY_MORE_ADJ, YY_SC_TO_UI, yy_start, and yytext_ptr.
Referenced by yylex().
static void yy_init_buffer (YY_BUFFER_STATE b, FILE * file) static
Definition at line 1330 of file lex.yy.c.
References yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_flush_buffer(), yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by yy_create_buffer(), and yyrestart().
static int yy_init_globals (void) static
Definition at line 1672 of file lex.yy.c.
References yy_buffer_stack, yy_buffer_stack_max, yy_buffer_stack_top, yy_c_buf_p, yy_init, yy_start, yyin, and yyout.
Referenced by yylex_destroy().
static void yy_load_buffer_state (void) static
Definition at line 1269 of file lex.yy.c.
References yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yy_hold_char, yy_n_chars, yyin, and yytext_ptr.
Referenced by yy_flush_buffer(), yy_switch_to_buffer(), yylex(), yypop_buffer_state(), yypush_buffer_state(), and yyrestart().
YY_BUFFER_STATE yy_scan_buffer (char * base, yy_size_t size)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters
base the character buffer
size the size in bytes of the character buffer
Returns
the newly allocated buffer state object.
Definition at line 1485 of file lex.yy.c.
References yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, yy_buffer_state::yy_n_chars, yy_switch_to_buffer(), and yyalloc().
Referenced by yy_scan_bytes().
YY_BUFFER_STATE yy_scan_bytes (char * yybytes, yy_size_t _yybytes_len)
Setup the input buffer state to scan the given bytes.
The next call to yylex() will scan from a copy of bytes.
Parameters
yybytes the byte buffer to scan
_yybytes_len the number of bytes in the buffer pointed to by bytes.
Returns
the newly allocated buffer state object.
Definition at line 1535 of file lex.yy.c.
References YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_is_our_buffer, yy_scan_buffer(), and yyalloc().
Referenced by yy_scan_string().
YY_BUFFER_STATE yy_scan_string (char * yystr)
Setup the input buffer state to scan a string.
The next call to yylex() will scan from a copy of str.
Parameters
yystr a NUL-terminated string to scan
Returns
the newly allocated buffer state object.
Note
If you want to scan bytes that may contain NUL values, then use yy_scan_bytes() instead.
Definition at line 1522 of file lex.yy.c.
References yy_scan_bytes().
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer)
Switch to a different input buffer.
Parameters
new_buffer The new input buffer.
Definition at line 1238 of file lex.yy.c.
References yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, yy_hold_char, yy_load_buffer_state(), yy_n_chars, and yyensure_buffer_stack().
Referenced by yy_scan_buffer().
static yy_state_type yy_try_NUL_trans (yy_state_type current_state) static
Definition at line 1082 of file lex.yy.c.
References yy_c_buf_p, yy_last_accepting_cpos, and yy_last_accepting_state.
Referenced by yylex().
void * yyalloc (yy_size_t size)
Definition at line 1746 of file lex.yy.c.
Referenced by yy_create_buffer(), yy_scan_buffer(), yy_scan_bytes(), and yyensure_buffer_stack().
static void yyensure_buffer_stack (void) static
Definition at line 1436 of file lex.yy.c.
References yy_buffer_stack, yy_buffer_stack_max, yy_buffer_stack_top, YY_FATAL_ERROR, yyalloc(), and yyrealloc().
Referenced by yy_switch_to_buffer(), yylex(), yypush_buffer_state(), and yyrestart().
void yyfree (void * ptr)
Definition at line 1763 of file lex.yy.c.
Referenced by yy_delete_buffer(), and yylex_destroy().
int yyget_debug (void)
Definition at line 1662 of file lex.yy.c.
References yy_flex_debug.
void* yyget_extra (void)
FILE * yyget_in (void)
Get the input stream.
Definition at line 1606 of file lex.yy.c.
References yyin.
yy_size_t yyget_leng (void)
Get the length of the current token.
Definition at line 1622 of file lex.yy.c.
References yyleng.
int yyget_lineno (void)
Get the current line number.
Definition at line 1597 of file lex.yy.c.
References yylineno.
FILE * yyget_out (void)
Get the output stream.
Definition at line 1614 of file lex.yy.c.
References yyout.
char * yyget_text (void)
Get the current token.
Definition at line 1631 of file lex.yy.c.
References yytext.
int yylex (void)
The main scanner function which does all the work.
Definition at line 639 of file lex.yy.c.
References ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, INITIAL, YY_BREAK, YY_BUF_SIZE, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yy_c_buf_p, yy_create_buffer(), YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yy_hold_char, yy_init, yy_last_accepting_cpos, yy_last_accepting_state, yy_load_buffer_state(), YY_MORE_ADJ, yy_n_chars, YY_NEW_FILE, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yyensure_buffer_stack(), yyin, yyout, yyterminate, yytext_ptr, and yywrap().
int yylex_destroy (void)
Definition at line 1701 of file lex.yy.c.
References yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_delete_buffer(), yy_init_globals(), yyfree(), and yypop_buffer_state().
void yypop_buffer_state (void)
Removes and deletes the top of the stack, if present.
The next element becomes the new top.
Definition at line 1417 of file lex.yy.c.
References yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_delete_buffer(), yy_did_buffer_switch_on_eof, and yy_load_buffer_state().
Referenced by yylex_destroy().
void yypush_buffer_state (YY_BUFFER_STATE new_buffer)
Pushes the new state onto the stack.
The new state becomes the current state. This function will allocate the stack if necessary.
Parameters
new_buffer The new state.
Definition at line 1387 of file lex.yy.c.
References yy_buffer_stack_top, yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, yy_hold_char, yy_load_buffer_state(), yy_n_chars, and yyensure_buffer_stack().
void * yyrealloc (void * ptr, yy_size_t size)
Definition at line 1751 of file lex.yy.c.
Referenced by yy_get_next_buffer(), and yyensure_buffer_stack().
void yyrestart (FILE * input_file)
Immediately switch to a different input stream.
Parameters
input_file A readable stream.
Note
This function does not reset the start condition to INITIAL .
Definition at line 1221 of file lex.yy.c.
References YY_BUF_SIZE, yy_create_buffer(), YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init_buffer(), yy_load_buffer_state(), yyensure_buffer_stack(), and yyin.
Referenced by input(), and yy_get_next_buffer().
void yyset_debug (int debug_flag)
Definition at line 1667 of file lex.yy.c.
void yyset_extra (void * user_defined)
void yyset_in (FILE * in_str)
Set the input stream.
This does not discard the current input buffer.
Parameters
in_str A readable stream.
See also
yy_switch_to_buffer
Definition at line 1652 of file lex.yy.c.
References yyin.
void yyset_lineno (int line_number)
Set the current line number.
Parameters
line_number
Definition at line 1640 of file lex.yy.c.
void yyset_out (FILE * out_str)
Definition at line 1657 of file lex.yy.c.
References yyout.
static void yyunput (int c, char * buf_ptr) static
static void yyunput (int c, register char * yy_bp) static
Definition at line 1105 of file lex.yy.c.
References source, yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, YY_FATAL_ERROR, yy_hold_char, yy_n_chars, and yytext_ptr.
int yywrap (void)
Referenced by input(), and yylex().
Variable Documentation
flex_int16_t yy_accept[21] static
Initial value:
=
    {   0,
        0,    0,   10,    9,    5,    6,    8,    9,    7,    8,
        8,    8,    1,    8,    7,    8,    4,    3,    2,    0
    }
Definition at line 372 of file lex.yy.c.
flex_int16_t yy_base[22] static
Initial value:
=
    {   0,
        0,    0,   23,   24,   24,   24,    0,   15,   14,    8,
        9,    4,    0,    0,   24,    8,    0,    0,    0,   24,
       15
    }
Definition at line 416 of file lex.yy.c.
YY_BUFFER_STATE* yy_buffer_stack = 0 static
Stack as an array.
Definition at line 255 of file lex.yy.c.
Referenced by yy_init_globals(), yyensure_buffer_stack(), and yylex_destroy().
size_t yy_buffer_stack_max = 0 static
capacity of stack.
Definition at line 254 of file lex.yy.c.
Referenced by yy_init_globals(), and yyensure_buffer_stack().
size_t yy_buffer_stack_top = 0 static
index of top of stack.
Definition at line 253 of file lex.yy.c.
Referenced by yy_init_globals(), yyensure_buffer_stack(), yypop_buffer_state(), and yypush_buffer_state().
char* yy_c_buf_p = (char *) 0 static
Definition at line 278 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), yy_get_previous_state(), yy_init_globals(), yy_load_buffer_state(), yy_switch_to_buffer(), yy_try_NUL_trans(), yylex(), yypush_buffer_state(), and yyunput().
flex_int16_t yy_chk[40] static
Initial value:
=
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   21,   16,   12,   11,   10,
        9,    8,    3,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20
    }
Definition at line 438 of file lex.yy.c.
flex_int16_t yy_def[22] static
Initial value:
=
    {   0,
       20,    1,   20,   20,   20,   20,   21,   20,   20,   21,
       21,   21,   21,   21,   20,   21,   21,   21,   21,    0,
       20
    }
Definition at line 423 of file lex.yy.c.
int yy_did_buffer_switch_on_eof static
Definition at line 285 of file lex.yy.c.
Referenced by input(), yy_switch_to_buffer(), yylex(), yypop_buffer_state(), and yypush_buffer_state().
flex_int32_t yy_ec[256] static
Definition at line 378 of file lex.yy.c.
int yy_flex_debug = 0
Definition at line 450 of file lex.yy.c.
Referenced by yyget_debug().
char yy_hold_char static
Definition at line 273 of file lex.yy.c.
Referenced by input(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex(), yypush_buffer_state(), and yyunput().
int yy_init = 0 static
Definition at line 279 of file lex.yy.c.
Referenced by yy_init_globals(), and yylex().
char* yy_last_accepting_cpos static
Definition at line 447 of file lex.yy.c.
Referenced by yy_get_previous_state(), yy_try_NUL_trans(), and yylex().
yy_state_type yy_last_accepting_state static
Definition at line 446 of file lex.yy.c.
Referenced by yy_get_previous_state(), yy_try_NUL_trans(), and yylex().
flex_int32_t yy_meta[16] static
Initial value:
=
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    }
Definition at line 410 of file lex.yy.c.
yy_size_t yy_n_chars static
Definition at line 274 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), yy_load_buffer_state(), yy_switch_to_buffer(), yylex(), yypush_buffer_state(), and yyunput().
flex_int16_t yy_nxt[40] static
Initial value:
=
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,    7,    7,
       11,    7,   12,    7,   13,   14,   19,   18,   17,   16,
       15,   15,   20,    3,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20
    }
Definition at line 430 of file lex.yy.c.
int yy_start = 0 static
Definition at line 280 of file lex.yy.c.
Referenced by yy_get_previous_state(), yy_init_globals(), and yylex().
FILE * yyin = (FILE *) 0
Definition at line 337 of file lex.yy.c.
Referenced by input(), yy_get_next_buffer(), yy_init_globals(), yy_load_buffer_state(), yyget_in(), yylex(), yyrestart(), and yyset_in().
yy_size_t yyleng
Definition at line 275 of file lex.yy.c.
Referenced by yyget_leng().
int yylineno = 1
Definition at line 343 of file lex.yy.c.
Referenced by yyget_lineno().
FILE * yyout = (FILE *) 0
Definition at line 337 of file lex.yy.c.
Referenced by yy_init_globals(), yyget_out(), yylex(), and yyset_out().
char * yytext
Definition at line 459 of file lex.yy.c.
Referenced by yyget_text().